"""
S&P 500 Constituents and Metadata
"""

SP500_COMPONENTS = [
    {"symbol": "BLK", "name": "BlackRock Inc.", "sector": "Financials", "industry": "Asset Management & Custody Banks"},
    {"symbol": "USB", "name": "U.S. Bancorp", "sector": "Financials", "industry": "Diversified Banks"},
    {"symbol": "AEP", "name": "American Electric Power Co. Inc.", "sector": "Utilities", "industry": "Electric Utilities"},
    {"symbol": "GOOG", "name": "Alphabet Inc. (Class C)", "sector": "Communication Services", "industry": "Interactive Media & Services"},
    {"symbol": "LUV", "name": "Southwest Airlines Co.", "sector": "Industrials", "industry": "Passenger Airlines"},
    {"symbol": "PKG", "name": "Packaging Corp. of America", "sector": "Materials", "industry": "Paper & Plastic Packaging Products & Materials"},
    {"symbol": "PSA", "name": "Public Storage", "sector": "Real Estate", "industry": "Self-Storage REITs"},
    {"symbol": "SNPS", "name": "Synopsys Inc.", "sector": "Information Technology", "industry": "Application Software"},
    {"symbol": "EMN", "name": "Eastman Chemical Co.", "sector": "Materials", "industry": "Specialty Chemicals"},
    {"symbol": "DXC", "name": "DXC Technology Co.", "sector": "Information Technology", "industry": "IT Consulting & Other Services"},
    {"symbol": "ELV", "name": "Elevance Health Inc.", "sector": "Health Care", "industry": "Managed Health Care"},
    {"symbol": "ON", "name": "ON Semiconductor Corp.", "sector": "Information Technology", "industry": "Semiconductors"},
    {"symbol": "PANW", "name": "Palo Alto Networks Inc.", "sector": "Information Technology", "industry": "Systems Software"},
    {"symbol": "PGR", "name": "Progressive Corp.", "sector": "Financials", "industry": "Property & Casualty Insurance"},
    {"symbol": "ICE", "name": "Intercontinental Exchange Inc.", "sector": "Financials", "industry": "Financial Exchanges & Data"},
    {"symbol": "FSLR", "name": "First Solar Inc.", "sector": "Information Technology", "industry": "Semiconductors"},
    {"symbol": "ROST", "name": "Ross Stores Inc.", "sector": "Consumer Discretionary", "industry": "Apparel Retail"},
    {"symbol": "PCG", "name": "PG&E Corp.", "sector": "Utilities", "industry": "Electric Utilities"},
    {"symbol": "GD", "name": "General Dynamics Corp.", "sector": "Industrials", "industry": "Aerospace & Defense"},
    {"symbol": "SWKS", "name": "Skyworks Solutions Inc.", "sector": "Information Technology", "industry": "Semiconductors"},
    {"symbol": "HLT", "name": "Hilton Worldwide Holdings Inc.", "sector": "Consumer Discretionary", "industry": "Hotels, Resorts & Cruise Lines"},
    {"symbol": "AMZN", "name": "Amazon.com Inc.", "sector": "Consumer Discretionary", "industry": "Broadline Retail"},
    {"symbol": "AJG", "name": "Arthur J. Gallagher & Co.", "sector": "Financials", "industry": "Insurance Brokers"},
    {"symbol": "EFX", "name": "Equifax Inc.", "sector": "Industrials", "industry": "Research & Consulting Services"},
    {"symbol": "JNJ", "name": "Johnson & Johnson", "sector": "Health Care", "industry": "Pharmaceuticals"},
    {"symbol": "STX", "name": "Seagate Technology Holdings plc", "sector": "Information Technology", "industry": "Technology Hardware, Storage & Peripherals"},
    {"symbol": "LLY", "name": "Eli Lilly & Co.", "sector": "Health Care", "industry": "Pharmaceuticals"},
    {"symbol": "HPQ", "name": "HP Inc.", "sector": "Information Technology", "industry": "Technology Hardware, Storage & Peripherals"},
    {"symbol": "GM", "name": "General Motors Co.", "sector": "Consumer Discretionary", "industry": "Automobile Manufacturers"},
    {"symbol": "FIS", "name": "Fidelity National Information Services Inc.", "sector": "Financials", "industry": "Transaction & Payment Processing Services"},
    {"symbol": "PCAR", "name": "PACCAR Inc.", "sector": "Industrials", "industry": "Construction Machinery & Heavy Transportation Equipment"},
    {"symbol": "GEN", "name": "Gen Digital Inc.", "sector": "Information Technology", "industry": "Systems Software"},
    {"symbol": "MOS", "name": "The Mosaic Co.", "sector": "Materials", "industry": "Fertilizers & Agricultural Chemicals"},
    {"symbol": "OXY", "name": "Occidental Petroleum Corp.", "sector": "Energy", "industry": "Oil & Gas Exploration & Production"},
    {"symbol": "WDAY", "name": "Workday Inc.", "sector": "Information Technology", "industry": "Application Software"},
    {"symbol": "SCHW", "name": "Charles Schwab Corp.", "sector": "Financials", "industry": "Investment Banking & Brokerage"},
    {"symbol": "UBER", "name": "Uber Technologies Inc.", "sector": "Industrials", "industry": "Passenger Ground Transportation"},
    {"symbol": "PNC", "name": "PNC Financial Services Group Inc.", "sector": "Financials", "industry": "Diversified Banks"},
    {"symbol": "PAYX", "name": "Paychex Inc.", "sector": "Industrials", "industry": "Human Resource & Employment Services"},
    {"symbol": "FMC", "name": "FMC Corp.", "sector": "Materials", "industry": "Fertilizers & Agricultural Chemicals"},
    {"symbol": "AME", "name": "AMETEK Inc.", "sector": "Industrials", "industry": "Electrical Components & Equipment"},
    {"symbol": "UNP", "name": "Union Pacific Corp.", "sector": "Industrials", "industry": "Rail Transportation"},
    {"symbol": "MSFT", "name": "Microsoft Corp.", "sector": "Information Technology", "industry": "Systems Software"},
    {"symbol": "AWK", "name": "American Water Works Co. Inc.", "sector": "Utilities", "industry": "Water Utilities"},
    {"symbol": "AXP", "name": "American Express Co.", "sector": "Financials", "industry": "Consumer Finance"},
    {"symbol": "JCI", "name": "Johnson Controls International plc", "sector": "Industrials", "industry": "Building Products"},
    {"symbol": "ENPH", "name": "Enphase Energy Inc.", "sector": "Information Technology", "industry": "Semiconductor Materials & Equipment"},
    {"symbol": "AKAM", "name": "Akamai Technologies Inc.", "sector": "Information Technology", "industry": "Internet Services & Infrastructure"},
    {"symbol": "RTX", "name": "RTX Corp.", "sector": "Industrials", "industry": "Aerospace & Defense"},
    {"symbol": "MMC", "name": "Marsh & McLennan Companies Inc.", "sector": "Financials", "industry": "Insurance Brokers"},
    {"symbol": "PH", "name": "Parker-Hannifin Corp.", "sector": "Industrials", "industry": "Industrial Machinery & Supplies & Components"},
    {"symbol": "HD", "name": "Home Depot Inc.", "sector": "Consumer Discretionary", "industry": "Home Improvement Retail"},
    {"symbol": "KDP", "name": "Keurig Dr Pepper Inc.", "sector": "Consumer Staples", "industry": "Soft Drinks & Non-alcoholic Beverages"},
    {"symbol": "TER", "name": "Teradyne Inc.", "sector": "Information Technology", "industry": "Semiconductor Materials & Equipment"},
    {"symbol": "CRM", "name": "Salesforce Inc.", "sector": "Information Technology", "industry": "Application Software"},
    {"symbol": "T", "name": "AT&T Inc.", "sector": "Communication Services", "industry": "Integrated Telecommunication Services"},
    {"symbol": "TEL", "name": "TE Connectivity Ltd.", "sector": "Information Technology", "industry": "Electronic Components"},
    {"symbol": "IDXX", "name": "IDEXX Laboratories Inc.", "sector": "Health Care", "industry": "Health Care Equipment"},
    {"symbol": "FLT", "name": "FLEETCOR Technologies Inc.", "sector": "Financials", "industry": "Transaction & Payment Processing Services"},
    {"symbol": "EW", "name": "Edwards Lifesciences Corp.", "sector": "Health Care", "industry": "Health Care Equipment"},
    {"symbol": "KVUE", "name": "Kenvue Inc.", "sector": "Consumer Staples", "industry": "Personal Care Products"},
    {"symbol": "MCD", "name": "McDonald's Corp.", "sector": "Consumer Discretionary", "industry": "Restaurants"},
    {"symbol": "GE", "name": "General Electric Co.", "sector": "Industrials", "industry": "Aerospace & Defense"},
    {"symbol": "TSLA", "name": "Tesla Inc.", "sector": "Consumer Discretionary", "industry": "Automobile Manufacturers"},
    {"symbol": "DXCM", "name": "DexCom Inc.", "sector": "Health Care", "industry": "Health Care Equipment"},
    {"symbol": "ES", "name": "Eversource Energy", "sector": "Utilities", "industry": "Electric Utilities"},
    {"symbol": "CMI", "name": "Cummins Inc.", "sector": "Industrials", "industry": "Construction Machinery & Heavy Transportation Equipment"},
    {"symbol": "DD", "name": "DuPont de Nemours Inc.", "sector": "Materials", "industry": "Specialty Chemicals"},
    {"symbol": "CARR", "name": "Carrier Global Corp.", "sector": "Industrials", "industry": "Building Products"},
    {"symbol": "TXN", "name": "Texas Instruments Inc.", "sector": "Information Technology", "industry": "Semiconductors"},
    {"symbol": "SBUX", "name": "Starbucks Corp.", "sector": "Consumer Discretionary", "industry": "Restaurants"},
    {"symbol": "CF", "name": "CF Industries Holdings Inc.", "sector": "Materials", "industry": "Fertilizers & Agricultural Chemicals"},
    {"symbol": "MS", "name": "Morgan Stanley", "sector": "Financials", "industry": "Investment Banking & Brokerage"},
    {"symbol": "PSX", "name": "Phillips 66", "sector": "Energy", "industry": "Oil & Gas Refining & Marketing"},
    {"symbol": "GILD", "name": "Gilead Sciences Inc.", "sector": "Health Care", "industry": "Biotechnology"},
    {"symbol": "BDX", "name": "Becton Dickinson and Co.", "sector": "Health Care", "industry": "Health Care Equipment"},
    {"symbol": "TMO", "name": "Thermo Fisher Scientific Inc.", "sector": "Health Care", "industry": "Life Sciences Tools & Services"},
    {"symbol": "CTVA", "name": "Corteva Inc.", "sector": "Materials", "industry": "Fertilizers & Agricultural Chemicals"},
    {"symbol": "ADBE", "name": "Adobe Inc.", "sector": "Information Technology", "industry": "Application Software"},
    {"symbol": "AON", "name": "Aon plc", "sector": "Financials", "industry": "Insurance Brokers"},
    {"symbol": "TRV", "name": "The Travelers Companies Inc.", "sector": "Financials", "industry": "Property & Casualty Insurance"},
    {"symbol": "PPG", "name": "PPG Industries Inc.", "sector": "Materials", "industry": "Specialty Chemicals"},
    {"symbol": "GLW", "name": "Corning Inc.", "sector": "Information Technology", "industry": "Electronic Components"},
    {"symbol": "XOM", "name": "Exxon Mobil Corp.", "sector": "Energy", "industry": "Integrated Oil & Gas"},
    {"symbol": "MCK", "name": "McKesson Corp.", "sector": "Health Care", "industry": "Health Care Distributors"},
    {"symbol": "ADM", "name": "Archer-Daniels-Midland Co.", "sector": "Consumer Staples", "industry": "Agricultural Products & Services"},
    {"symbol": "HON", "name": "Honeywell International Inc.", "sector": "Industrials", "industry": "Industrial Conglomerates"},
    {"symbol": "NKE", "name": "Nike Inc.", "sector": "Consumer Discretionary", "industry": "Apparel, Accessories & Luxury Goods"},
    {"symbol": "MCHP", "name": "Microchip Technology Inc.", "sector": "Information Technology", "industry": "Semiconductors"},
    {"symbol": "CDNS", "name": "Cadence Design Systems Inc.", "sector": "Information Technology", "industry": "Application Software"},
    {"symbol": "QCOM", "name": "QUALCOMM Inc.", "sector": "Information Technology", "industry": "Semiconductors"},
    {"symbol": "ILMN", "name": "Illumina Inc.", "sector": "Health Care", "industry": "Life Sciences Tools & Services"},
    {"symbol": "COF", "name": "Capital One Financial Corp.", "sector": "Financials", "industry": "Consumer Finance"},
    {"symbol": "CME", "name": "CME Group Inc.", "sector": "Financials", "industry": "Financial Exchanges & Data"},
    {"symbol": "FAST", "name": "Fastenal Co.", "sector": "Industrials", "industry": "Trading Companies & Distributors"},
    {"symbol": "CMCSA", "name": "Comcast Corp.", "sector": "Communication Services", "industry": "Cable & Satellite"},
    {"symbol": "SYK", "name": "Stryker Corp.", "sector": "Health Care", "industry": "Health Care Equipment"},
    {"symbol": "CSX", "name": "CSX Corp.", "sector": "Industrials", "industry": "Rail Transportation"},
    {"symbol": "EPAM", "name": "EPAM Systems Inc.", "sector": "Information Technology", "industry": "IT Consulting & Other Services"},
    {"symbol": "WDC", "name": "Western Digital Corp.", "sector": "Information Technology", "industry": "Technology Hardware, Storage & Peripherals"},
    {"symbol": "ACN", "name": "Accenture plc", "sector": "Information Technology", "industry": "IT Consulting & Other Services"},
    {"symbol": "DLR", "name": "Digital Realty Trust Inc.", "sector": "Real Estate", "industry": "Data Center REITs"},
    {"symbol": "JNPR", "name": "Juniper Networks Inc.", "sector": "Information Technology", "industry": "Communications Equipment"},
    {"symbol": "VMC", "name": "Vulcan Materials Co.", "sector": "Materials", "industry": "Construction Materials"},
    {"symbol": "WEC", "name": "WEC Energy Group Inc.", "sector": "Utilities", "industry": "Multi-Utilities"},
    {"symbol": "WMT", "name": "Walmart Inc.", "sector": "Consumer Staples", "industry": "Consumer Staples Merchandise Retail"},
    {"symbol": "DOW", "name": "Dow Inc.", "sector": "Materials", "industry": "Commodity Chemicals"},
    {"symbol": "APD", "name": "Air Products and Chemicals Inc.", "sector": "Materials", "industry": "Industrial Gases"},
    {"symbol": "APP", "name": "AppLovin Corp.", "sector": "Information Technology", "industry": "Application Software"},
    {"symbol": "PFE", "name": "Pfizer Inc.", "sector": "Health Care", "industry": "Pharmaceuticals"},
    {"symbol": "TJX", "name": "TJX Companies Inc.", "sector": "Consumer Discretionary", "industry": "Apparel Retail"},
    {"symbol": "EOG", "name": "EOG Resources Inc.", "sector": "Energy", "industry": "Oil & Gas Exploration & Production"},
    {"symbol": "A", "name": "Agilent Technologies Inc.", "sector": "Health Care", "industry": "Life Sciences Tools & Services"},
    {"symbol": "AAPL", "name": "Apple Inc.", "sector": "Information Technology", "industry": "Technology Hardware, Storage & Peripherals"},
    {"symbol": "VZ", "name": "Verizon Communications Inc.", "sector": "Communication Services", "industry": "Integrated Telecommunication Services"},
    {"symbol": "NFLX", "name": "Netflix Inc.", "sector": "Communication Services", "industry": "Movies & Entertainment"},
    {"symbol": "O", "name": "Realty Income Corp.", "sector": "Real Estate", "industry": "Retail REITs"},
    {"symbol": "BAC", "name": "Bank of America Corp.", "sector": "Financials", "industry": "Diversified Banks"},
    {"symbol": "PG", "name": "Procter & Gamble Co.", "sector": "Consumer Staples", "industry": "Household Products"},
    {"symbol": "MNST", "name": "Monster Beverage Corp.", "sector": "Consumer Staples", "industry": "Soft Drinks & Non-alcoholic Beverages"},
    {"symbol": "SRE", "name": "Sempra", "sector": "Utilities", "industry": "Multi-Utilities"},
    {"symbol": "ROP", "name": "Roper Technologies Inc.", "sector": "Information Technology", "industry": "Application Software"},
    {"symbol": "FTNT", "name": "Fortinet Inc.", "sector": "Information Technology", "industry": "Systems Software"},
    {"symbol": "VRSK", "name": "Verisk Analytics Inc.", "sector": "Industrials", "industry": "Research & Consulting Services"},
    {"symbol": "UNH", "name": "UnitedHealth Group Inc.", "sector": "Health Care", "industry": "Managed Health Care"},
    {"symbol": "MU", "name": "Micron Technology Inc.", "sector": "Information Technology", "industry": "Semiconductors"},
    {"symbol": "ALL", "name": "The Allstate Corp.", "sector": "Financials", "industry": "Property & Casualty Insurance"},
    {"symbol": "MPC", "name": "Marathon Petroleum Corp.", "sector": "Energy", "industry": "Oil & Gas Refining & Marketing"},
    {"symbol": "INTU", "name": "Intuit Inc.", "sector": "Information Technology", "industry": "Application Software"},
    {"symbol": "EQIX", "name": "Equinix Inc.", "sector": "Real Estate", "industry": "Data Center REITs"},
    {"symbol": "ABBV", "name": "AbbVie Inc.", "sector": "Health Care", "industry": "Biotechnology"},
    {"symbol": "AMAT", "name": "Applied Materials Inc.", "sector": "Information Technology", "industry": "Semiconductor Materials & Equipment"},
    {"symbol": "NVDA", "name": "NVIDIA Corp.", "sector": "Information Technology", "industry": "Semiconductors"},
    {"symbol": "AZO", "name": "AutoZone Inc.", "sector": "Consumer Discretionary", "industry": "Automotive Retail"},
    {"symbol": "LULU", "name": "Lululemon Athletica Inc.", "sector": "Consumer Discretionary", "industry": "Apparel Retail"},
    {"symbol": "MAR", "name": "Marriott International Inc.", "sector": "Consumer Discretionary", "industry": "Hotels, Resorts & Cruise Lines"},
    {"symbol": "STZ", "name": "Constellation Brands Inc.", "sector": "Consumer Staples", "industry": "Distillers & Vintners"},
    {"symbol": "PRU", "name": "Prudential Financial Inc.", "sector": "Financials", "industry": "Life & Health Insurance"},
    {"symbol": "AMCR", "name": "Amcor plc", "sector": "Materials", "industry": "Paper & Plastic Packaging Products & Materials"},
    {"symbol": "MLM", "name": "Martin Marietta Materials Inc.", "sector": "Materials", "industry": "Construction Materials"},
    {"symbol": "AMT", "name": "American Tower Corp.", "sector": "Real Estate", "industry": "Telecom Tower REITs"},
    {"symbol": "TDY", "name": "Teledyne Technologies Inc.", "sector": "Industrials", "industry": "Aerospace & Defense"},
    {"symbol": "NOC", "name": "Northrop Grumman Corp.", "sector": "Industrials", "industry": "Aerospace & Defense"},
    {"symbol": "MANH", "name": "Manhattan Associates Inc.", "sector": "Information Technology", "industry": "Application Software"},
    {"symbol": "ANET", "name": "Arista Networks Inc.", "sector": "Information Technology", "industry": "Communications Equipment"},
    {"symbol": "FI", "name": "Fiserv Inc.", "sector": "Financials", "industry": "Transaction & Payment Processing Services"},
    {"symbol": "BA", "name": "Boeing Co.", "sector": "Industrials", "industry": "Aerospace & Defense"},
    {"symbol": "WELL", "name": "Welltower Inc.", "sector": "Real Estate", "industry": "Health Care REITs"},
    {"symbol": "HES", "name": "Hess Corp.", "sector": "Energy", "industry": "Oil & Gas Exploration & Production"},
    {"symbol": "AIG", "name": "American International Group Inc.", "sector": "Financials", "industry": "Property & Casualty Insurance"},
    {"symbol": "IP", "name": "International Paper Co.", "sector": "Materials", "industry": "Paper & Plastic Packaging Products & Materials"},
    {"symbol": "GS", "name": "Goldman Sachs Group Inc.", "sector": "Financials", "industry": "Investment Banking & Brokerage"},
    {"symbol": "APO", "name": "Apollo Global Management Inc.", "sector": "Financials", "industry": "Asset Management & Custody Banks"},
    {"symbol": "FDX", "name": "FedEx Corp.", "sector": "Industrials", "industry": "Air Freight & Logistics"},
    {"symbol": "K", "name": "Kellanova", "sector": "Consumer Staples", "industry": "Packaged Foods & Meats"},
    {"symbol": "AMGN", "name": "Amgen Inc.", "sector": "Health Care", "industry": "Biotechnology"},
    {"symbol": "WBA", "name": "Walgreens Boots Alliance Inc.", "sector": "Consumer Staples", "industry": "Drug Retail"},
    {"symbol": "ABNB", "name": "Airbnb Inc.", "sector": "Consumer Discretionary", "industry": "Hotels, Resorts & Cruise Lines"},
    {"symbol": "GPN", "name": "Global Payments Inc.", "sector": "Financials", "industry": "Transaction & Payment Processing Services"},
    {"symbol": "CAT", "name": "Caterpillar Inc.", "sector": "Industrials", "industry": "Construction Machinery & Heavy Transportation Equipment"},
    {"symbol": "ORCL", "name": "Oracle Corp.", "sector": "Information Technology", "industry": "Application Software"},
    {"symbol": "ETN", "name": "Eaton Corporation plc", "sector": "Industrials", "industry": "Electrical Components & Equipment"},
    {"symbol": "ED", "name": "Consolidated Edison Inc.", "sector": "Utilities", "industry": "Multi-Utilities"},
    {"symbol": "CL", "name": "Colgate-Palmolive Co.", "sector": "Consumer Staples", "industry": "Household Products"},
    {"symbol": "AFL", "name": "Aflac Inc.", "sector": "Financials", "industry": "Life & Health Insurance"},
    {"symbol": "META", "name": "Meta Platforms Inc.", "sector": "Communication Services", "industry": "Interactive Media & Services"},
    {"symbol": "C", "name": "Citigroup Inc.", "sector": "Financials", "industry": "Diversified Banks"},
    {"symbol": "SOLV", "name": "Solventum Corp.", "sector": "Health Care", "industry": "Health Care Technology"},
    {"symbol": "MSTR", "name": "MicroStrategy Inc.", "sector": "Information Technology", "industry": "Application Software"},
    {"symbol": "ABT", "name": "Abbott Laboratories", "sector": "Health Care", "industry": "Health Care Equipment"},
    {"symbol": "ZBRA", "name": "Zebra Technologies Corp.", "sector": "Information Technology", "industry": "Electronic Equipment & Instruments"},
    {"symbol": "CRWD", "name": "CrowdStrike Holdings Inc.", "sector": "Information Technology", "industry": "Systems Software"},
    {"symbol": "BMY", "name": "Bristol-Myers Squibb Co.", "sector": "Health Care", "industry": "Pharmaceuticals"},
    {"symbol": "BRK.B", "name": "Berkshire Hathaway Inc.", "sector": "Financials", "industry": "Multi-Sector Holdings"},
    {"symbol": "OTIS", "name": "Otis Worldwide Corp.", "sector": "Industrials", "industry": "Industrial Machinery & Supplies & Components"},
    {"symbol": "VRTX", "name": "Vertex Pharmaceuticals Inc.", "sector": "Health Care", "industry": "Biotechnology"},
    {"symbol": "DIS", "name": "Walt Disney Co.", "sector": "Communication Services", "industry": "Movies & Entertainment"},
    {"symbol": "XEL", "name": "Xcel Energy Inc.", "sector": "Utilities", "industry": "Electric Utilities"},
    {"symbol": "CI", "name": "The Cigna Group", "sector": "Health Care", "industry": "Health Care Services"},
    {"symbol": "IFF", "name": "International Flavors & Fragrances Inc.", "sector": "Materials", "industry": "Specialty Chemicals"},
    {"symbol": "IT", "name": "Gartner Inc.", "sector": "Information Technology", "industry": "IT Consulting & Other Services"},
    {"symbol": "GIS", "name": "General Mills Inc.", "sector": "Consumer Staples", "industry": "Packaged Foods & Meats"},
    {"symbol": "EMR", "name": "Emerson Electric Co.", "sector": "Industrials", "industry": "Electrical Components & Equipment"},
    {"symbol": "D", "name": "Dominion Energy Inc.", "sector": "Utilities", "industry": "Electric Utilities"},
    {"symbol": "DAL", "name": "Delta Air Lines Inc.", "sector": "Industrials", "industry": "Passenger Airlines"},
    {"symbol": "AMD", "name": "Advanced Micro Devices Inc.", "sector": "Information Technology", "industry": "Semiconductors"},
    {"symbol": "SMCI", "name": "Super Micro Computer Inc.", "sector": "Information Technology", "industry": "Technology Hardware, Storage & Peripherals"},
    {"symbol": "NSC", "name": "Norfolk Southern Corp.", "sector": "Industrials", "industry": "Rail Transportation"},
    {"symbol": "MO", "name": "Altria Group Inc.", "sector": "Consumer Staples", "industry": "Tobacco"},
    {"symbol": "DE", "name": "Deere & Co.", "sector": "Industrials", "industry": "Agricultural & Farm Machinery"},
    {"symbol": "NEM", "name": "Newmont Corp.", "sector": "Materials", "industry": "Gold"},
    {"symbol": "ORLY", "name": "O'Reilly Automotive Inc.", "sector": "Consumer Discretionary", "industry": "Automotive Retail"},
    {"symbol": "KMB", "name": "Kimberly-Clark Corp.", "sector": "Consumer Staples", "industry": "Household Products"},
    {"symbol": "ALB", "name": "Albemarle Corp.", "sector": "Materials", "industry": "Specialty Chemicals"},
    {"symbol": "GEV", "name": "GE Vernova Inc.", "sector": "Industrials", "industry": "Heavy Electrical Equipment"},
    {"symbol": "KKR", "name": "KKR & Co. Inc.", "sector": "Financials", "industry": "Asset Management & Custody Banks"},
    {"symbol": "PM", "name": "Philip Morris International Inc.", "sector": "Consumer Staples", "industry": "Tobacco"},
    {"symbol": "JKHY", "name": "Jack Henry & Associates Inc.", "sector": "Financials", "industry": "Transaction & Payment Processing Services"},
    {"symbol": "ITW", "name": "Illinois Tool Works Inc.", "sector": "Industrials", "industry": "Industrial Machinery & Supplies & Components"},
    {"symbol": "FCX", "name": "Freeport-McMoRan Inc.", "sector": "Materials", "industry": "Copper"},
    {"symbol": "ISRG", "name": "Intuitive Surgical Inc.", "sector": "Health Care", "industry": "Health Care Equipment"},
    {"symbol": "ADI", "name": "Analog Devices Inc.", "sector": "Information Technology", "industry": "Semiconductors"},
    {"symbol": "CE", "name": "Celanese Corp.", "sector": "Materials", "industry": "Specialty Chemicals"},
    {"symbol": "SO", "name": "Southern Co.", "sector": "Utilities", "industry": "Electric Utilities"},
    {"symbol": "TDY", "name": "Teledyne Technologies Inc.", "sector": "Information Technology", "industry": "Electronic Equipment & Instruments"},
    {"symbol": "UPS", "name": "United Parcel Service Inc.", "sector": "Industrials", "industry": "Air Freight & Logistics"},
    {"symbol": "MDLZ", "name": "Mondelez International Inc.", "sector": "Consumer Staples", "industry": "Packaged Foods & Meats"},
    {"symbol": "PEP", "name": "PepsiCo Inc.", "sector": "Consumer Staples", "industry": "Soft Drinks & Non-alcoholic Beverages"},
    {"symbol": "NEE", "name": "NextEra Energy Inc.", "sector": "Utilities", "industry": "Electric Utilities"},
    {"symbol": "CTAS", "name": "Cintas Corp.", "sector": "Industrials", "industry": "Diversified Support Services"},
    {"symbol": "KLAC", "name": "KLA Corp.", "sector": "Information Technology", "industry": "Semiconductor Materials & Equipment"},
    {"symbol": "ECL", "name": "Ecolab Inc.", "sector": "Materials", "industry": "Specialty Chemicals"},
    {"symbol": "GOOGL", "name": "Alphabet Inc. (Class A)", "sector": "Communication Services", "industry": "Interactive Media & Services"},
    {"symbol": "NXPI", "name": "NXP Semiconductors N.V.", "sector": "Information Technology", "industry": "Semiconductors"},
    {"symbol": "MSI", "name": "Motorola Solutions Inc.", "sector": "Information Technology", "industry": "Communications Equipment"},
    {"symbol": "PTC", "name": "PTC Inc.", "sector": "Information Technology", "industry": "Application Software"},
    {"symbol": "JPM", "name": "JPMorgan Chase & Co.", "sector": "Financials", "industry": "Diversified Banks"},
    {"symbol": "LRCX", "name": "Lam Research Corp.", "sector": "Information Technology", "industry": "Semiconductor Materials & Equipment"},
    {"symbol": "AVGO", "name": "Broadcom Inc.", "sector": "Information Technology", "industry": "Semiconductors"},
    {"symbol": "NUE", "name": "Nucor Corp.", "sector": "Materials", "industry": "Steel"},
    {"symbol": "MPWR", "name": "Monolithic Power Systems Inc.", "sector": "Information Technology", "industry": "Semiconductors"},
    {"symbol": "HPE", "name": "Hewlett Packard Enterprise Co.", "sector": "Information Technology", "industry": "Technology Hardware, Storage & Peripherals"},
    {"symbol": "BKNG", "name": "Booking Holdings Inc.", "sector": "Consumer Discretionary", "industry": "Hotels, Resorts & Cruise Lines"},
    {"symbol": "NOW", "name": "ServiceNow Inc.", "sector": "Information Technology", "industry": "Systems Software"},
    {"symbol": "HSY", "name": "The Hershey Co.", "sector": "Consumer Staples", "industry": "Packaged Foods & Meats"},
    {"symbol": "CNC", "name": "Centene Corp.", "sector": "Health Care", "industry": "Managed Health Care"},
    {"symbol": "WFC", "name": "Wells Fargo & Co.", "sector": "Financials", "industry": "Diversified Banks"},
    {"symbol": "LIN", "name": "Linde plc", "sector": "Materials", "industry": "Industrial Gases"},
    {"symbol": "BSX", "name": "Boston Scientific Corp.", "sector": "Health Care", "industry": "Health Care Equipment"},
    {"symbol": "APH", "name": "Amphenol Corp.", "sector": "Information Technology", "industry": "Electronic Components"},
    {"symbol": "CCI", "name": "Crown Castle Inc.", "sector": "Real Estate", "industry": "Telecom Tower REITs"},
    {"symbol": "SLB", "name": "Schlumberger Ltd.", "sector": "Energy", "industry": "Oil & Gas Equipment & Services"},
    {"symbol": "CVS", "name": "CVS Health Corp.", "sector": "Health Care", "industry": "Health Care Services"},
    {"symbol": "ANSS", "name": "ANSYS Inc.", "sector": "Information Technology", "industry": "Application Software"},
    {"symbol": "F", "name": "Ford Motor Co.", "sector": "Consumer Discretionary", "industry": "Automobile Manufacturers"},
    {"symbol": "TYL", "name": "Tyler Technologies Inc.", "sector": "Information Technology", "industry": "Application Software"},
    {"symbol": "COST", "name": "Costco Wholesale Corp.", "sector": "Consumer Staples", "industry": "Consumer Staples Merchandise Retail"},
    {"symbol": "FFIV", "name": "F5 Inc.", "sector": "Information Technology", "industry": "Communications Equipment"},
    {"symbol": "CSCO", "name": "Cisco Systems Inc.", "sector": "Information Technology", "industry": "Communications Equipment"},
    {"symbol": "VLO", "name": "Valero Energy Corp.", "sector": "Energy", "industry": "Oil & Gas Refining & Marketing"},
    {"symbol": "CVX", "name": "Chevron Corp.", "sector": "Energy", "industry": "Integrated Oil & Gas"},
    {"symbol": "ROK", "name": "Rockwell Automation Inc.", "sector": "Industrials", "industry": "Electrical Components & Equipment"},
    {"symbol": "DECK", "name": "Deckers Outdoor Corp.", "sector": "Consumer Discretionary", "industry": "Footwear"},
    {"symbol": "KEYS", "name": "Keysight Technologies Inc.", "sector": "Information Technology", "industry": "Electronic Equipment & Instruments"},
    {"symbol": "WM", "name": "Waste Management Inc.", "sector": "Industrials", "industry": "Environmental & Facilities Services"},
    {"symbol": "MET", "name": "MetLife Inc.", "sector": "Financials", "industry": "Life & Health Insurance"},
    {"symbol": "BIIB", "name": "Biogen Inc.", "sector": "Health Care", "industry": "Biotechnology"},
    {"symbol": "CB", "name": "Chubb Ltd.", "sector": "Financials", "industry": "Property & Casualty Insurance"},
    {"symbol": "LMT", "name": "Lockheed Martin Corp.", "sector": "Industrials", "industry": "Aerospace & Defense"},
    {"symbol": "CPAY", "name": "Corpay Inc.", "sector": "Financials", "industry": "Transaction & Payment Processing Services"},
    {"symbol": "VRSN", "name": "VeriSign Inc.", "sector": "Information Technology", "industry": "Internet Services & Infrastructure"},
    {"symbol": "HWM", "name": "Howmet Aerospace Inc.", "sector": "Industrials", "industry": "Aerospace & Defense"},
    {"symbol": "LOW", "name": "Lowe's Companies Inc.", "sector": "Consumer Discretionary", "industry": "Home Improvement Retail"},
    {"symbol": "CTSH", "name": "Cognizant Technology Solutions Corp.", "sector": "Information Technology", "industry": "IT Consulting & Other Services"},
    {"symbol": "NTAP", "name": "NetApp Inc.", "sector": "Information Technology", "industry": "Technology Hardware, Storage & Peripherals"},
    {"symbol": "UAL", "name": "United Airlines Holdings Inc.", "sector": "Industrials", "industry": "Passenger Airlines"},
    {"symbol": "BX", "name": "Blackstone Inc.", "sector": "Financials", "industry": "Asset Management & Custody Banks"},
    {"symbol": "COP", "name": "ConocoPhillips", "sector": "Energy", "industry": "Oil & Gas Exploration & Production"},
    {"symbol": "MRK", "name": "Merck & Co. Inc.", "sector": "Health Care", "industry": "Pharmaceuticals"},
    {"symbol": "HUM", "name": "Humana Inc.", "sector": "Health Care", "industry": "Managed Health Care"},
    {"symbol": "LYB", "name": "LyondellBasell Industries N.V.", "sector": "Materials", "industry": "Commodity Chemicals"},
    {"symbol": "ZTS", "name": "Zoetis Inc.", "sector": "Health Care", "industry": "Pharmaceuticals"},
    {"symbol": "PLTR", "name": "Palantir Technologies Inc.", "sector": "Information Technology", "industry": "Application Software"},
    {"symbol": "SHW", "name": "Sherwin-Williams Co.", "sector": "Materials", "industry": "Specialty Chemicals"},
    {"symbol": "KO", "name": "Coca-Cola Co.", "sector": "Consumer Staples", "industry": "Soft Drinks & Non-alcoholic Beverages"},
    {"symbol": "QRVO", "name": "Qorvo Inc.", "sector": "Information Technology", "industry": "Semiconductors"},
    {"symbol": "PYPL", "name": "PayPal Holdings Inc.", "sector": "Financials", "industry": "Transaction & Payment Processing Services"},
    {"symbol": "TT", "name": "Trane Technologies plc", "sector": "Industrials", "industry": "Building Products"},
    {"symbol": "V", "name": "Visa Inc.", "sector": "Financials", "industry": "Transaction & Payment Processing Services"},
    {"symbol": "MA", "name": "Mastercard Inc.", "sector": "Financials", "industry": "Transaction & Payment Processing Services"},
    {"symbol": "DUK", "name": "Duke Energy Corp.", "sector": "Utilities", "industry": "Electric Utilities"},
    {"symbol": "SPG", "name": "Simon Property Group Inc.", "sector": "Real Estate", "industry": "Retail REITs"},
    {"symbol": "TDG", "name": "TransDigm Group Inc.", "sector": "Industrials", "industry": "Aerospace & Defense"},
    {"symbol": "PLD", "name": "Prologis Inc.", "sector": "Real Estate", "industry": "Industrial REITs"},
    {"symbol": "MDT", "name": "Medtronic plc", "sector": "Health Care", "industry": "Health Care Equipment"},
    {"symbol": "BALL", "name": "Ball Corp.", "sector": "Materials", "industry": "Metal, Glass & Plastic Containers"},
    {"symbol": "IBM", "name": "International Business Machines Corp.", "sector": "Information Technology", "industry": "IT Consulting & Other Services"},
    {"symbol": "REGN", "name": "Regeneron Pharmaceuticals Inc.", "sector": "Health Care", "industry": "Biotechnology"},
    {"symbol": "EXC", "name": "Exelon Corp.", "sector": "Utilities", "industry": "Electric Utilities"},
    {"symbol": "SPGI", "name": "S&P Global Inc.", "sector": "Financials", "industry": "Financial Exchanges & Data"},
]

SP500_SYMBOLS = [c["symbol"] for c in SP500_COMPONENTS]

def get_sp500_symbols():
    return SP500_SYMBOLS

def get_sp500_metadata(symbol):
    for comp in SP500_COMPONENTS:
        if comp["symbol"] == symbol:
            return comp
    return {"symbol": symbol, "name": symbol, "sector": "Other", "industry": "Other"}
